version: "3"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins:/var/jenkins_home"
    networks:
      - net
networks:
  net: